/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: the9thearl (https://sketchfab.com/the9thearl)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mars-free-low-poly-0781cd3ab59c4e6f94ae68d28fbf30a8
Title: Mars, Free, low-poly
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { Group } from 'three'

import MarsScene from '../../public/assets/mars_planet.glb';

interface MarsProps {
    [key: string]: any;
}
const Mars: React.FC<MarsProps> = (props) => {
  const [isClient, setIsClient] = useState(false);
  const marsRef = useRef<Group>(null);
  const { nodes, materials } = useGLTF(MarsScene);

  useEffect(() => {
    // This will only run on the client side
    setIsClient(true);
  }, []);

  if (!isClient) {
    // Return null or a fallback component during SSR
    return null;
  }

  return (
    <a.group ref={marsRef} {...props}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.LowpolyMars_lowpolymarsmat_0.geometry}
            material={materials.lowpolymarsmat}
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5000, 5000.001, 5000]}
          />
        </group>
      </group>
    </a.group>
  )
}

export default Mars;