/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: the9thearl (https://sketchfab.com/the9thearl)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mars-free-low-poly-0781cd3ab59c4e6f94ae68d28fbf30a8
Title: Mars, Free, low-poly
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, Html, PresentationControls } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { Group, BackSide, ShaderMaterial } from 'three'
import { extend} from '@react-three/fiber';
import { createPortal } from 'react-dom'
import { useDrag } from '@use-gesture/react'

import MarsScene from '../../public/assets/mars_planet.glb';
import { Console } from 'console'

// Add this before the Mars component
// Custom outline shader material
const OutlineMaterial = new ShaderMaterial({
  uniforms: {
    outlineColor: { value: [1, 1, 1] }, // White color
    outlineThickness: { value: 0.01 }
  },
  vertexShader: `
    uniform float outlineThickness;
    void main() {
      vec4 pos = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      vec3 norm = normalize(normalMatrix * normal);
      pos.xyz += norm * outlineThickness;
      gl_Position = pos;
    }
  `,
  fragmentShader: `
    uniform vec3 outlineColor;
    void main() {
      gl_FragColor = vec4(outlineColor, 1.0);
    }
  `,
  side: BackSide
});

extend({ OutlineMaterial })

interface MarsProps {
  position: [number, number, number];
  scale: [number, number, number];
  rotation: [number, number, number];
  onClick?: () => void;
  enableControls?: boolean;
  onAnnotationClick?: (annotation: {
    title: string;
    description: string;
    extraInfo?: string;
  }) => void;
}
const Mars: React.FC<MarsProps> = ({ onClick, enableControls, onAnnotationClick, ...props}) => {
  const [isClient, setIsClient] = useState(false);
  const planetRef = useRef<Group>(null);
  const { nodes, materials } = useGLTF(MarsScene);
  const [hovered, setHovered] = useState(false);
  const [rotation, setRotation] = useState([0, 0, 0])
  const [isDragging, setIsDragging] = useState(false)
  const [selectedAnnotation, setSelectedAnnotation] = useState<null | {
    title: string;
    description: string;
    extraInfo?: string;
  }>(null);

  useEffect(() => {
    setIsClient(true);
  }, [materials, nodes]);

  if (!isClient) {
    // Return null or a fallback component during SSR
    return null;
  }

  const handleAnnotationClick = (annotation: typeof annotations[0]) => {
    if (onAnnotationClick) {
      onAnnotationClick(annotation);
    }
    setSelectedAnnotation(annotation);
  };

  // Add annotation data
  // Use smaller values that match your model's scale
  const annotations = [
    {
      position: [50, 0, 0],
      title: "Olympus Mons",
      description: "Largest volcano in the solar system",
      extraInfo: "Standing 21.9 km high and 600 km in diameter, Olympus Mons is the largest known volcano in the solar system. To put this in perspective, it's about three times as tall as Mount Everest!"
    },
    {
      position: [0, 50, 0],
      title: "North Pole",
      description: "Ice caps containing water and CO2",
      extraInfo: "Mars' polar ice caps consist of both water ice and dry ice (frozen CO2). During winter, up to 30% of Mars' atmosphere freezes into these caps."
    },
    {
      position: [0, 0, 50],
      title: "Valles Marineris",
      description: "Largest canyon in the solar system",
      extraInfo: "At 4,000 km long and up to 7 km deep, Valles Marineris would stretch from New York to California if placed on Earth. It's believed to have formed by ancient tectonic activity."
    }
  ];

  return (
    <>
    {enableControls ? (
      <PresentationControls
      global
      config={{ mass: 2, tension: 400 }}
      >
      <a.group ref={planetRef}>
    {hovered && (
      <Html
        position={[0, -100, 0]}
        className="pointer-events-none"
        center
        distanceFactor={8}
        transform
        sprite
      >
        <div className="bg-black bg-opacity-50 rounded-lg px-4 py-2 text-white text-1024">
          Projects
        </div>
      </Html>
    )}
    {/* Annotation points */}
    {annotations.map((annotation, index) => (
          <Html
            key={index}
            position={annotation.position}
            distanceFactor={200}
            occlude
            style={{
              transition: 'all 0.2s',
              opacity: hovered ? 1 : 0.8,
              transform: `scale(${hovered ? 1.2 : 1})`
            }}
          >
            <div className="annotation-point"
            onClick={() => handleAnnotationClick(annotation)}>
              <div className="annotation-dot" />
              <div className="annotation-label">
                <strong>{annotation.title}</strong>
                <br />
                {annotation.description}
              </div>
            </div>
          </Html>
        ))}
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
        {/* Original Mars mesh */}
        <mesh
          geometry={nodes.LowpolyMars_lowpolymarsmat_0.geometry}
          material={materials.lowpolymarsmat}
          position={[0, 0, 100]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[5000, 5000.001, 5000]}
        />
        {/* Outline mesh that only shows when hovered */}
        {hovered && (
          <mesh
            geometry={nodes.LowpolyMars_lowpolymarsmat_0.geometry}
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5050, 5050.001, 5050]} // Slightly larger scale for outline
          >
            <shaderMaterial
              attach="material"
              {...OutlineMaterial}
              transparent
              depthWrite={false}
            />
          </mesh>
        )}
      </group>
    </group>
      </a.group>
      </PresentationControls>
    ) : (
      <a.group 
      ref={planetRef}
      {...props}
      onClick={onClick}
      onPointerOver={() => setHovered(true)}
      onPointerOut={() => setHovered(false)}
      >
    {hovered && (
      <Html
        position={[0, -100, 0]}
        className="pointer-events-none"
        center
        distanceFactor={8}
        transform
        sprite
      >
        <div className="bg-black bg-opacity-50 rounded-lg px-4 py-2 text-white text-1024">
          Projects
        </div>
      </Html>
    )}
    {/* Annotation points */}
    {annotations.map((annotation, index) => (
          <Html
            key={index}
            position={annotation.position}
            distanceFactor={200}
            occlude
            style={{
              transition: 'all 0.2s',
              opacity: hovered ? 1 : 0.8,
              transform: `scale(${hovered ? 1.2 : 1})`
            }}
          >
            <div className="annotation-point"
            onClick={() => handleAnnotationClick(annotation)}>
              <div className="annotation-dot" />
              <div className="annotation-label">
                <strong>{annotation.title}</strong>
                <br />
                {annotation.description}
              </div>
            </div>
          </Html>
        ))}
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
        {/* Original Mars mesh */}
        <mesh
          geometry={nodes.LowpolyMars_lowpolymarsmat_0.geometry}
          material={materials.lowpolymarsmat}
          position={[0, 0, 100]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[5000, 5000.001, 5000]}
        />
        {/* Outline mesh that only shows when hovered */}
        {hovered && (
          <mesh
            geometry={nodes.LowpolyMars_lowpolymarsmat_0.geometry}
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5050, 5050.001, 5050]} // Slightly larger scale for outline
          >
            <shaderMaterial
              attach="material"
              {...OutlineMaterial}
              transparent
              depthWrite={false}
            />
          </mesh>
        )}
      </group>
    </group>
      </a.group>
    )}
    
  </>
  );
}

export default Mars;