/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: the9thearl (https://sketchfab.com/the9thearl)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mars-free-low-poly-0781cd3ab59c4e6f94ae68d28fbf30a8
Title: Mars, Free, low-poly
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { Group, BackSide, ShaderMaterial } from 'three'
import { Html } from '@react-three/drei';
import { extend } from '@react-three/fiber';

const PlanetScene = '/assets/the_moon.glb';

// Add this before the Mars component
// Custom outline shader material
const OutlineMaterial = new ShaderMaterial({
  uniforms: {
    outlineColor: { value: [1, 1, 1] }, // White color
    outlineThickness: { value: 0.01 }
  },
  vertexShader: `
    uniform float outlineThickness;
    void main() {
      vec4 pos = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      vec3 norm = normalize(normalMatrix * normal);
      pos.xyz += norm * outlineThickness;
      gl_Position = pos;
    }
  `,
  fragmentShader: `
    uniform vec3 outlineColor;
    void main() {
      gl_FragColor = vec4(outlineColor, 1.0);
    }
  `,
  side: BackSide
});

extend({ OutlineMaterial })

interface PlanetProps {
    [key: string]: any;
}
const Moon: React.FC<PlanetProps> = (props) => {
  const [isClient, setIsClient] = useState(false);
  const planetRef = useRef<Group>(null);
  const { nodes, materials } = useGLTF(PlanetScene);
  const [hovered, setHovered] = useState(false);

  // Add Rotation Animatiopn
  useFrame((state, delta) => {
    if(planetRef.current) {
      planetRef.current.rotation.y += delta * 0.02;
      planetRef.current.rotation.x = Math.PI * 0.1;
    }
  });

  useEffect(() => {
    console.log('Moon materials:', materials);
    console.log('Moon nodes:', nodes);
    setIsClient(true);
  }, [materials, nodes]);

  if (!isClient) {
    // Return null or a fallback component during SSR
    return null;
  }

  return (
    <a.group 
    ref={planetRef} 
    {...props}
    onPointerOver={() => setHovered(true)}
    onPointerOut={() => setHovered(false)}
  >
    {hovered && (
      <Html
        position={[0, 2, 0]}
        className="pointer-events-none"
        center
        distanceFactor={8}
      >
        <div className="bg-black bg-opacity-50 rounded-lg px-4 py-2 text-white text-1024">
          Moon
        </div>
      </Html>
    )}
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
        {/* Original Moon mesh */}
        <mesh
          geometry={nodes.defaultMaterial.geometry}
          material={materials.Material__50}
          position={[0, 0, 100]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[5000, 5000.001, 5000]}
        />
        {/* Outline mesh that only shows when hovered */}
        {hovered && (
          <mesh
            geometry={nodes.defaultMaterial.geometry} 
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={[5050, 5050.001, 5050]} // Slightly larger scale for outline
          >
            <shaderMaterial
              attach="material"
              {...OutlineMaterial}
              transparent
              depthWrite={false}
            />
          </mesh>
        )}
      </group>
    </group>
  </a.group>
  );
}

export default Moon;

useGLTF.preload(PlanetScene);