/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/assets/moon.glb --types --transform --tsx 
Files: public/assets/moon.glb [20.85MB] > D:\Source\iamty\Documents\GitHub\Portfolio\3d_portfolio\moon-transformed.glb [138.05KB] (99%)
Author: Akshat (https://sketchfab.com/shooter24994)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/moon-4db2273f6dd943b8ad7fa5e3b1b2431a
Title: Moon
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { Group, BackSide, ShaderMaterial } from 'three'
import { Html } from '@react-three/drei';
import { extend } from '@react-three/fiber';
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Sphere_Material002_0: THREE.Mesh
  }
  materials: {
    ['Material.002']: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Moon(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/assets/moon.glb') as GLTFResult

   // Add rotation animation
   useFrame((state, delta) => {
    if (group.current) {
      group.current.rotation.y += delta * 0.02
    }
  })

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere_Material002_0.geometry} 
      material={materials['Material.002']} 
      rotation={[-Math.PI / 2, 0, 0]} 
      scale={100} />
    </group>
  )
}

useGLTF.preload('/assets/moon.glb')

export default Moon;
