/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: the9thearl (https://sketchfab.com/the9thearl)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mars-free-low-poly-0781cd3ab59c4e6f94ae68d28fbf30a8
Title: Mars, Free, low-poly
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, Html, PresentationControls } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { Group, BackSide, ShaderMaterial, Mesh, Object3D, Material, MeshStandardMaterial, MeshPhysicalMaterial, FrontSide, DoubleSide } from 'three';
import { GLTF } from 'three-stdlib';
import { extend} from '@react-three/fiber';

// Custom outline shader material
const createOutlineMaterial = (side: 'front' | 'back') => new ShaderMaterial({
  uniforms: {
    outlineColor: { value: [1, 1, 1] },
    outlineThickness: { value: 0.01 }
  },
  vertexShader: `
    uniform float outlineThickness;
    void main() {
      vec4 pos = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      vec3 norm = normalize(normalMatrix * normal);
      pos.xyz += norm * outlineThickness;
      gl_Position = pos;
    }
  `,
  fragmentShader: `
    uniform vec3 outlineColor;
    void main() {
      gl_FragColor = vec4(outlineColor, 0.9);
    }
  `,
  side: side === 'front' ? FrontSide : BackSide,
  transparent: true,
  depthTest: true,
  depthWrite: false
});

export interface PlanetAnnotation {
  position: [number, number, number];
  title: string;
  description: string;
  extraInfo?: string;
}

export interface PlanetConfig {
  name: string;
  modelPath: string;
  meshName: string;
  materialName: string;
  annotations: PlanetAnnotation[];
  scale: [number, number, number];
  outlineScale: [number, number, number];
  outlineSide?: 'front' | 'back';
  color?: string;
  hoverText?: string;
}

// extend({ OutlineMaterial })

interface PlanetProps {
  config: PlanetConfig;
  position: [number, number, number];
  rotation: [number, number, number];
  onClick?: () => void;
  enableControls?: boolean;
  onAnnotationClick?: (annotation: {
    title: string;
    description: string;
    extraInfo?: string;
  }) => void;
  isHovered?: boolean;
  onHoverStart?: () => void;
  onHoverEnd?: () => void;
}
const Planet: React.FC<PlanetProps> = ({ 
  config, 
  onClick, 
  enableControls, 
  onAnnotationClick,
  isHovered,
  onHoverStart,
  onHoverEnd,
  ...props 
}) => {
  const [isClient, setIsClient] = useState(false);
  const planetRef = useRef<Group>(null);
  const { nodes, materials } = useGLTF(config.modelPath);
  // const [hovered, setHovered] = useState(false);
  const [rotation, setRotation] = useState([0, 0, 0])
  const [isDragging, setIsDragging] = useState(false)
  const [selectedAnnotation, setSelectedAnnotation] = useState<null | {
    title: string;
    description: string;
    extraInfo?: string;
  }>(null);

  useEffect(() => {
    setIsClient(true);
    if (nodes && materials) {
      console.log('Config:', config.name);
      console.log('Node names:', nodes);
      console.log('Material names:', materials);
      console.log('Looking for mesh:', config.meshName);
      console.log('Looking for material:', config.materialName);
    }
  }, [materials, nodes, config.modelPath]);

  if (!isClient) {
    // Return null or a fallback component during SSR
    return null;
  }

  const handleAnnotationClick = (annotation: PlanetAnnotation) => {
    if (onAnnotationClick) {
      onAnnotationClick(annotation);
    }
    setSelectedAnnotation(annotation);
  };

  let planetMesh = nodes[config.meshName] as Mesh;
  let planetMaterial = materials[config.materialName] as Material;

  if (!planetMesh || !planetMaterial) {
    console.error(`Failed to load ${config.name} model:`, {
      meshFound: !!planetMesh,
      materialFound: !!planetMaterial,
      availableNodes: Object.keys(nodes),
      availableMaterials: Object.keys(materials)
    });
    return null;
  }

  return (
    <>
    {isHovered && (
        <Html
        position={[0, -100, 0]}
        className="pointer-events-none"
        center
        distanceFactor={8}
        sprite
      >
        <div className="bg-black bg-opacity-50 rounded-lg px-4 py-2 text-white text-1024 whitespace-nowrap">
          {config.hoverText || config.name}
        </div>
      </Html> 
    )}
    {enableControls ? (
      <PresentationControls
      global
      config={{ mass: 2, tension: 400 }}
      >
    <a.group ref={planetRef}>

    {/* Annotation points */}
    {config.annotations.map((annotation, index) => (
          <Html
            key={index}
            position={annotation.position}
            distanceFactor={200}
            occlude
            style={{
              transition: 'all 0.2s',
              opacity: isHovered ? 1 : 0.8,
              transform: `scale(${isHovered ? 1.2 : 1})`
            }}
          >
            <div className="annotation-point"
            onClick={() => handleAnnotationClick(annotation)}>
              <div className="annotation-dot" />
              <div className="annotation-label">
                <strong>{annotation.title}</strong>
                <br />
                {annotation.description}
              </div>
            </div>
          </Html>
        ))}
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
        {/* Original Mars mesh */}
        <mesh
          geometry={planetMesh?.geometry}
          material={planetMaterial}
          position={[0, 0, 100]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={config.scale}
        />
        {/* Outline mesh that only shows when hovered */}
        {isHovered && (
          <mesh
            geometry={planetMesh?.geometry}
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={config.outlineScale} // Slightly larger scale for outline
          >
            <shaderMaterial
              attach="material"
              {...createOutlineMaterial(config.outlineSide || 'back')}
              transparent
              depthWrite={false}
            />
          </mesh>
        )}
      </group>
    </group>
      </a.group>
      </PresentationControls>
    ) : (
    <a.group 
    ref={planetRef}
    {...props}
    onClick={onClick}
    onPointerOver={onHoverStart}
    onPointerOut={onHoverEnd}
    >
    
    {/* Annotation points */}
    {config.annotations.map((annotation, index) => (
          <Html
            key={index}
            position={annotation.position}
            distanceFactor={200}
            occlude
            style={{
              transition: 'all 0.2s',
              opacity: isHovered ? 1 : 0.8,
              transform: `scale(${isHovered ? 1.2 : 1})`
            }}
          >
            <div className="annotation-point"
            onClick={() => handleAnnotationClick(annotation)}>
              <div className="annotation-dot" />
              <div className="annotation-label">
                <strong>{annotation.title}</strong>
                <br />
                {annotation.description}
              </div>
            </div>
          </Html>
        ))}
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
        {/* Original Mars mesh */}
        <mesh
          geometry={planetMesh?.geometry}
          material={planetMaterial}
          position={[0, 0, 100]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={config.scale}
        />
        {/* Outline mesh that only shows when hovered */}
        {isHovered && (
          <mesh
            geometry={planetMesh?.geometry}
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={config.outlineScale} // Slightly larger scale for outline
          >
            <shaderMaterial
              attach="material"
              {...createOutlineMaterial(config.outlineSide || 'back')}
              transparent
              depthWrite={false}
            />
          </mesh>
        )}
      </group>
    </group>
    </a.group>
    )}
  </>
  );
}

useGLTF.preload('/assets/mars_planet.glb');
useGLTF.preload('/assets/the_moon.glb');
useGLTF.preload('/assets/earth.glb');

export default Planet;

