/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: the9thearl (https://sketchfab.com/the9thearl)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/mars-free-low-poly-0781cd3ab59c4e6f94ae68d28fbf30a8
Title: Mars, Free, low-poly
*/

import React, { useRef, useEffect, useState } from 'react'
import { useGLTF, Html, PresentationControls } from '@react-three/drei'
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'
import { Group, BackSide, ShaderMaterial, Mesh, Object3D, Material, MeshStandardMaterial, MeshPhysicalMaterial, FrontSide, DoubleSide } from 'three';
import { GLTF } from 'three-stdlib';
import { extend} from '@react-three/fiber';
import * as THREE from 'three';

// Custom outline shader material
const createOutlineMaterial = (side: 'front' | 'back') => new ShaderMaterial({
  uniforms: {
    outlineColor: { value: [1, 1, 1] },
    outlineThickness: { value: 0.01 }
  },
  vertexShader: `
    uniform float outlineThickness;
    void main() {
      vec4 pos = projectionMatrix * modelViewMatrix * vec4(position, 1.0);
      vec3 norm = normalize(normalMatrix * normal);
      pos.xyz += norm * outlineThickness;
      gl_Position = pos;
    }
  `,
  fragmentShader: `
    uniform vec3 outlineColor;
    void main() {
      gl_FragColor = vec4(outlineColor, 0.9);
    }
  `,
  side: side === 'front' ? FrontSide : BackSide,
  transparent: true,
  depthTest: true,
  depthWrite: false
});

export interface PlanetAnnotation {
  position: [number, number, number];
  title: string;
  description: string;
  extraInfo?: string;
  customContent?: React.ReactNode;
}

export interface PlanetConfig {
  name: string;
  modelPath: string;
  meshName: string;
  materialName: string;
  annotations: PlanetAnnotation[];
  scale: [number, number, number];
  outlineScale: [number, number, number];
  outlineSide?: 'front' | 'back';
  color?: string;
  hoverText?: string;
  hoverPosition?: [number, number, number];
}

interface PlanetProps {
  config: PlanetConfig;
  position: [number, number, number];
  rotation: [number, number, number];
  onClick?: () => void;
  enableControls?: boolean;
  onAnnotationClick?: (annotation: {
    title: string;
    description: string;
    extraInfo?: string;
  }) => void;
  isHovered?: boolean;
  onHoverStart?: () => void;
  onHoverEnd?: () => void;
  autoRotate?: boolean;
  focusedAnnotationIndex?: number;
}
const Planet: React.FC<PlanetProps> = ({ 
  config, 
  onClick, 
  enableControls, 
  onAnnotationClick,
  isHovered,
  onHoverStart,
  onHoverEnd,
  autoRotate,
  focusedAnnotationIndex,
  ...props 
}) => {
  const [isClient, setIsClient] = useState(false);
  const planetRef = useRef<Group>(null);
  const { nodes, materials } = useGLTF(config.modelPath);
  // const [hovered, setHovered] = useState(false);
  const [rotation, setRotation] = useState([0, 0, 0])
  const [isDragging, setIsDragging] = useState(false)
  const [selectedAnnotation, setSelectedAnnotation] = useState<null | {
    title: string;
    description: string;
    extraInfo?: string;
  }>(null);

  useFrame(() => {
    if (autoRotate && planetRef.current) {
      planetRef.current.rotation.y += 0.001;
      planetRef.current.rotation.x -= 0.001;
    }

    // Handle annotation focusing
    if (focusedAnnotationIndex !== undefined && planetRef.current && enableControls) {
      const annotation = config.annotations[focusedAnnotationIndex];
      // Create vectors for calculation
      const annotationPos = new THREE.Vector3(...annotation.position);
      const cameraDirection = new THREE.Vector3(0, 0, 1); // Camera looks toward positive Z
      
      // We want to rotate the planet so that the annotation faces the camera
      // This means the annotation should be in the direction opposite to camera
      const targetDirection = annotationPos.clone().normalize().multiplyScalar(-1);
      
      // Calculate required rotations
      const targetY = Math.atan2(targetDirection.x, targetDirection.z);
      const targetX = Math.asin(-targetDirection.y); // Negative because we want to bring it forward
      
      const lerpFactor = 0.05;
      
      // Apply Y rotation with wrapping
      let deltaY = targetY - planetRef.current.rotation.y;
      while (deltaY > Math.PI) deltaY -= 2 * Math.PI;
      while (deltaY < -Math.PI) deltaY += 2 * Math.PI;
      
      planetRef.current.rotation.y += deltaY * lerpFactor;
      planetRef.current.rotation.x += (targetX - planetRef.current.rotation.x) * lerpFactor;
      
      // Clamp X rotation
      planetRef.current.rotation.x = Math.max(-Math.PI/2, Math.min(Math.PI/2, planetRef.current.rotation.x));
    }
  })

  useEffect(() => {
    setIsClient(true);
    if (nodes && materials) {
      console.log('Config:', config.name);
      console.log('Node names:', nodes);
      console.log('Material names:', materials);
      console.log('Looking for mesh:', config.meshName);
      console.log('Looking for material:', config.materialName);
    }
  }, [materials, nodes, config.name, config.meshName, config.materialName]);

  if (!isClient) {
    // Return null or a fallback component during SSR
    return null;
  }

  const handleAnnotationClick = (annotation: PlanetAnnotation) => {
    if (onAnnotationClick) {
      onAnnotationClick(annotation);
    }
    setSelectedAnnotation(annotation);
  };

  let planetMesh = nodes[config.meshName] as Mesh;
  let planetMaterial = materials[config.materialName] as Material;

  if (!planetMesh || !planetMaterial) {
    console.error(`Failed to load ${config.name} model:`, {
      meshFound: !!planetMesh,
      materialFound: !!planetMaterial,
      availableNodes: Object.keys(nodes),
      availableMaterials: Object.keys(materials)
    });
    return null;
  }

  // Extract shared components to eliminate duplication
  const PlanetLabel = () => {
    let labelPosition: [number, number, number] = config.hoverPosition || [0, 0, 0];
    if (enableControls) { labelPosition = [0, -70, 0]; }

    return (
    <Html
      position={labelPosition || [0, 0, 0]}
      className="pointer-events-none"
      center
      distanceFactor={8}
      sprite
    >
      <div className="bg-black bg-opacity-50 rounded-lg px-4 py-2 text-white text-1024 whitespace-nowrap">
        {config.hoverText || config.name}
      </div>
    </Html>
    );
};

  const AnnotationPoints = () => (
    <>
      {config.annotations.map((annotation, index) => (
        <Html
          key={index}
          position={annotation.position}
          distanceFactor={200}
          occlude
          style={{
            transition: 'all 0.2s',
            opacity: isHovered ? 1 : 0.8,
            transform: `scale(${isHovered ? 1.2 : 1.0})`
          }}
        >
          <div 
            className="annotation-point"
            onClick={() => handleAnnotationClick(annotation)}
          >
            <div className="annotation-dot" />
            <div className="annotation-label">
              <strong>{annotation.title}</strong>
              <br />
              {annotation.description}
            </div>
          </div>
        </Html>
      ))}
    </>
  );

  const PlanetMesh = () => (
    <group rotation={[-Math.PI / 2, 0, 0]}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.01}>
        {/* Original planet mesh */}
        <mesh
          geometry={planetMesh?.geometry}
          material={planetMaterial}
          position={[0, 0, 100]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={config.scale}
        />
        {/* Outline mesh that only shows when hovered */}
        {isHovered && (
          <mesh
            geometry={planetMesh?.geometry}
            position={[0, 0, 100]}
            rotation={[0, 0, -Math.PI / 2]}
            scale={config.outlineScale}
          >
            <shaderMaterial
              attach="material"
              {...createOutlineMaterial(config.outlineSide || 'back')}
              transparent
              depthWrite={false}
            />
          </mesh>
        )}
      </group>
    </group>
  );

  const PlanetContent = () => (
    <>
      <AnnotationPoints />
      <PlanetMesh />
    </>
  );

  return (
    <>
      <PlanetLabel />
      {enableControls ? (
        <PresentationControls
          global
          config={{ mass: 2, tension: 400 }}
        >
          <a.group ref={planetRef}>
            <PlanetContent />
          </a.group>
        </PresentationControls>
      ) : (
        <a.group 
          ref={planetRef}
          {...props}
          onClick={onClick}
          onPointerOver={onHoverStart}
          onPointerOut={onHoverEnd}
        >
          <PlanetContent />
        </a.group>
      )}
    </>
  );
}

useGLTF.preload('/assets/mars_planet.glb');
useGLTF.preload('/assets/the_moon.glb');
useGLTF.preload('/assets/earth.glb');

export default Planet;

